### PR TITLE
Add license header

### PR DESCRIPTION
**Pull request by XhmikosR**
This requires #14 to be merged **first**.

### CODE REVIEW

**Comment by stml** [comment]
A bit confused by these conflicts following previous commits. Can you have another look?

**Comment by XhmikosR** [comment]
It's because you wrongfully merged #8 and then merged master to #14. You should **not** have merged #8. Anyway, I'll try to fix the issues and revert any unneeded stuff.

**Comment by XhmikosR** [comment]
Fixed now. I also enforced LF so that there are no useless changes on Windows.

**Comment by XhmikosR** [comment]
@stml: ping

**Pull request closed without merging**
